name: UI Automation Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-ui-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Use fallback .env
        run: cp .env.example .env

      - name: Set browser environment
        run: echo "BROWSER=${{ matrix.browser }}" >> $GITHUB_ENV

      - name: Run BDD tests
        run: npm run test:gherkin

      - name: Generate HTML report
        run: npm run report:html

      - name: Upload HTML report as artifact (v4)
        uses: actions/upload-artifact@v4
        with:
          name: UI-Test-Report-${{ matrix.browser }}
          path: cucumber-report
          overwrite: true

  deploy-report:
    needs: run-ui-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Regenerate HTML report (optional)
        run: npm run report:html

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: cucumber-report
          publish_branch: gh-pages
