permissions:
  contents: write

name: UI Automation Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-ui-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Use fallback .env
        run: cp .env.example .env

      - name: Set browser environment
        run: echo "BROWSER=${{ matrix.browser }}" >> $GITHUB_ENV

      - name: Run BDD tests
        run: npm run test:gherkin

      - name: Generate HTML report
        run: npm run report:html

      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: UI-Test-Report-${{ matrix.browser }}
          path: cucumber-report/${{ matrix.browser }}
          overwrite: true

  deploy-report:
    needs: run-ui-tests
    runs-on: ubuntu-latest

    steps:
      - name: Download Chromium report
        uses: actions/download-artifact@v4
        with:
          name: UI-Test-Report-chromium
          path: publish/chromium

      - name: Download Firefox report
        uses: actions/download-artifact@v4
        with:
          name: UI-Test-Report-firefox
          path: publish/firefox

      - name: Add landing page
        run: |
          mkdir -p publish
          echo '<!DOCTYPE html><html><head><title>UI Test Reports</title></head><body><h1>Test Reports</h1><ul><li><a href="./chromium/">Chromium Report</a></li><li><a href="./firefox/">Firefox Report</a></li></ul></body></html>' > publish/index.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: publish
          publish_branch: gh-pages
